name: Build Windows Wheels

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_wheels:
    name: Build Wheels
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.11"
          channels: conda-forge,defaults
          channel-priority: strict

      - name: Create conda environment
        run: conda create -n build-env python=3.11 -y
        
      - name: activate conda environment
        run: conda activate build-env
        
      - name: Install Conda dependencies
        run: |
          conda install -n build-env -y rocksdb cython setuptools wheel libpython m2w64-toolchain
          pip install cython  # Redundant but ensures it's available
          # python -m cython
          # python cython --version
          
      - name: Change directory to project root
        run: cd ${{ github.workspace }}  # Ensures you're in the project directory
        
      - name: Generate C++ Files
        run: |
          python -m cython rocksdb/rocksdb.pyx  # Ensure rocksdb.cpp is created
      - name: Check if rocksdb.cpp exists
        run: |
          dir rocksdb
          mv rocksdb/rocksdb.c rocksdb/rocksdb.cpp


      - name: Build wheel
        run: |
          conda run -n build-env python setup.py build_ext --inplace
          conda run -n build-env python setup.py bdist_wheel

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rocksdb-wheels
          path: |
            dist/*.whl
            wheelhouse/*.whl
          retention-days: 3
