name: Build Windows Wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  create_conda_env:
    name: Create Conda Environment
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.11"
        channels: conda-forge,defaults
        channel-priority: strict

    - name: Initialize conda
      shell: bash
      run: |
        eval "$(conda shell.bash hook)"

    - name: Create and activate conda environment
      shell: bash
      run: |
        conda create -n build-env python=3.11 -y
        source "$(conda info --base)/etc/profile.d/conda.sh"
        conda activate build-env

  build_wheels:
    name: Build Wheel
    runs-on: windows-latest
    needs: create_conda_env
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.11"
        channels: conda-forge,defaults
        channel-priority: strict

    - name: Initialize conda
      shell: bash
      run: |
        eval "$(conda shell.bash hook)"

    - name: Activate conda environment
      shell: bash
      run: |
        source "$(conda info --base)/etc/profile.d/conda.sh"
        conda activate build-env

    - name: Install Conda dependencies
      shell: bash
      run: |
        conda install -y rocksdb cython setuptools wheel libpython m2w64-toolchain

    - name: Verify RocksDB installation
      shell: bash
      run: |
        dir %CONDA_PREFIX%/Library/include/rocksdb && dir %CONDA_PREFIX%/Library/lib/rocksdb.lib

    - name: Build wheel
      shell: bash
      env:
        INCLUDE: "%CONDA_PREFIX%/Library/include;%INCLUDE%"
        LIB: "%CONDA_PREFIX%/Library/lib;%LIB%"
        CFLAGS: "-I%CONDA_PREFIX%/Library/include /D_WIN32_WINNT=0x0601"
        CXXFLAGS: "-I%CONDA_PREFIX%/Library/include /EHsc /D_WIN32_WINNT=0x0601"
      run: |
        conda run -n build-env python setup.py build_ext --inplace
        conda run -n build-env python setup.py bdist_wheel

    - name: Repair wheel (if needed)
      shell: bash
      run: |
        pip install delvewheel
        delvewheel repair dist/*.whl --add-path %CONDA_PREFIX%/Library/bin

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rocksdb-wheels
        path: |
          dist/*.whl
          wheelhouse/*.whl
        retention-days: 3
