
name: Build Windows Wheel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_wheel:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel cibuildwheel

      - name: Build wheel with cibuildwheel
        run: |
          cibuildwheel --platform win --output-dir wheelhouse .

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-wheel
          path: wheelhouse/*.whl
