name: Build Windows Wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  set_conda_path:
    name: Set Conda Path
    runs-on: windows-latest
    outputs:
      conda_path: ${{ steps.set_conda.outputs.path }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      id: conda
      with:
        auto-update-conda: true
        python-version: "3.11"
        channels: conda-forge,defaults
        channel-priority: strict

    - name: Set Conda Path
      shell: cmd
      run: |
        echo "CONDA_PATH=$CONDA" >> $GITHUB_ENV
        echo "path=$CONDA" >> $GITHUB_OUTPUT

  create_conda_env:
    name: Create Conda Environment
    runs-on: windows-latest
    needs: set_conda_path
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create conda environment
      shell: cmd
      env:
        CONDA_PATH: ${{ needs.set_conda_path.outputs.path }}
      run: |
        "%CONDA_PATH%\conda.exe" create -n build-env python=3.11 -y

  build_wheels:
    name: Build Wheel
    runs-on: windows-latest
    needs: create_conda_env
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Conda dependencies
      shell: cmd
      env:
        CONDA_PATH: ${{ needs.set_conda_path.outputs.path }}
      run: |
        "%CONDA_PATH%\conda.exe" install -n build-env -y rocksdb cython setuptools wheel libpython m2w64-toolchain

    - name: Build wheel
      shell: cmd
      env:
        CONDA_PATH: ${{ needs.set_conda_path.outputs.path }}
        INCLUDE: "%CONDA_PREFIX%\\Library\\include;%INCLUDE%"
        LIB: "%CONDA_PREFIX%\\Library\\lib;%LIB%"
      run: |
        "%CONDA_PATH%\conda.exe" run -n build-env python setup.py build_ext --inplace
        "%CONDA_PATH%\conda.exe" run -n build-env python setup.py bdist_wheel

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rocksdb-wheels
        path: |
          dist/*.whl
          wheelhouse/*.whl
        retention-days: 3
